import * as THREE from 'three';
import { canEat, chooseTarget, createLevelConfig, getStarSpeed, nextLevelState } from './game/rules.js';
import './styles.css';
import './mobile-controls.css';
import './mobile-layout.css';

const canvas = document.querySelector('#game-canvas');
const scene = new THREE.Scene();
scene.fog = new THREE.FogExp2(0x0b2527, 0.018);
const camera = new THREE.PerspectiveCamera(48, innerWidth / innerHeight, .1, 200);
const renderer = new THREE.WebGLRenderer({ canvas, antialias: true, powerPreference: 'high-performance' });
renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.setSize(innerWidth, innerHeight); renderer.shadowMap.enabled = true;
scene.add(new THREE.HemisphereLight(0x9cf4d6, 0x07151d, 2.2));
const moon = new THREE.DirectionalLight(0xc5fff0, 3.2); moon.position.set(-9, 16, 6); moon.castShadow = true; scene.add(moon);
const world = new THREE.Group(); const actors = new THREE.Group(); world.add(actors); scene.add(world);
const keys = new Set(); let running = false; let paused = false; let soundOn = true; let audioCtx = null; let masterGain = null; let musicTimer = null;
let touchInput = { x: 0, z: 0, boost: false }; let pulseQueued = false;
let state = { level: 1, stars: 1, eaten: 0 }; let player; let boss; let creatures = []; let decor = []; let last = performance.now();
const mat = (color, roughness=.6, emissive=0) => new THREE.MeshStandardMaterial({ color, roughness, metalness:.08, emissive, emissiveIntensity: emissive ? 1.3 : 0 });
const palette = { mist: [0x133b3b,0x68dcb8,0x8cffb7], crystal:[0x132d48,0x6dbbff,0xb0f6ff], ember:[0x42211f,0xff8b55,0xffd085], moss:[0x183c2b,0x9bdc65,0xd4ff9a], marsh:[0x27324c,0xb08bff,0xd7c7ff], storm:[0x1d2941,0x7596ff,0xc5d8ff], ruins:[0x473f35,0xcaa36a,0xffe4a4], frost:[0x244b63,0x94e2ff,0xe5fbff], void:[0x27193f,0xe779ff,0xffb7f7], crown:[0x4a3620,0xffcc4d,0xfff1a0] };
const creatureTypes = ['beetle','bird','crab','fox','frog','manta','mole','ram','turtle','wyrm'];
function ensureAudio(){ const C=window.AudioContext||window.webkitAudioContext; if(!soundOn||!C)return null; if(!audioCtx){audioCtx=new C();masterGain=audioCtx.createGain();masterGain.gain.value=.14;masterGain.connect(audioCtx.destination)} if(audioCtx.state==='suspended')audioCtx.resume(); if(!musicTimer){let step=0;musicTimer=setInterval(()=>{if(!soundOn||!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='triangle';o.frequency.value=[196,246.94,293.66,246.94][step++%4];g.gain.setValueAtTime(.0001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.055,audioCtx.currentTime+.04);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+1.1);o.connect(g).connect(masterGain);o.start();o.stop(audioCtx.currentTime+1.15)},1200)} return audioCtx; }
function sfx(freq=280,duration=.07){const ac=ensureAudio();if(!ac)return;const o=ac.createOscillator(),g=ac.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.15,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+duration);o.connect(g).connect(masterGain);o.start();o.stop(ac.currentTime+duration)}
function labelSprite(text,color='#dfffee'){const c=document.createElement('canvas');c.width=256;c.height=64;const x=c.getContext('2d');x.font='bold 22px monospace';x.textAlign='center';x.fillStyle='rgba(4,19,24,.82)';x.roundRect(8,8,240,48,16);x.fill();x.fillStyle=color;x.fillText(text,128,39);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,depthTest:false}));s.scale.set(2.4,.6,1);s.position.y=2.5;return s}
function shapeMesh(type,color){const g=new THREE.Group();const body=mat(color,.45,color);const eye=mat(0x07151d);let main;
 if(type==='beetle'){main=new THREE.Mesh(new THREE.SphereGeometry(1,8,6),body);main.scale.set(1.3,.6,.9);for(const x of [-.7,-.35,.35,.7]){const l=new THREE.Mesh(new THREE.CylinderGeometry(.05,.09,.8,5),body);l.rotation.z=Math.PI/2.6;l.position.set(x*.7,-.25,0);g.add(l)}}
 if(type==='bird'){main=new THREE.Mesh(new THREE.ConeGeometry(1,2.2,6),body);main.rotation.z=-Math.PI/2;main.scale.set(1,.8,.7);}
 if(type==='crab'){main=new THREE.Mesh(new THREE.DodecahedronGeometry(1,0),body);main.scale.set(1.2,.7,.8);[-1,1].forEach(side=>{const claw=new THREE.Mesh(new THREE.TorusGeometry(.3,.08,5,8,Math.PI),body);claw.position.set(side*1,.15,.55);claw.rotation.y=side*Math.PI/2;g.add(claw)})}
 if(type==='fox'){main=new THREE.Mesh(new THREE.ConeGeometry(1,1.8,5),body);main.scale.set(1,.75,1.2);main.rotation.x=-Math.PI/2}
 if(type==='frog'){main=new THREE.Mesh(new THREE.SphereGeometry(1,10,6),body);main.scale.set(1.15,.65,1);}
 if(type==='manta'){main=new THREE.Mesh(new THREE.ConeGeometry(1,2.3,4),body);main.rotation.x=Math.PI/2;main.scale.set(1.5,.35,1)}
 if(type==='mole'){main=new THREE.Mesh(new THREE.ConeGeometry(1,1.7,6),body);main.rotation.x=Math.PI/2;main.scale.set(1,.8,1)}
 if(type==='ram'){main=new THREE.Mesh(new THREE.IcosahedronGeometry(1,0),body);main.scale.set(1.1,.8,.9);for(const side of [-1,1]){const horn=new THREE.Mesh(new THREE.TorusGeometry(.32,.08,6,10,Math.PI*1.4),body);horn.position.set(side*.75,.25,.35);horn.rotation.z=side*.5;g.add(horn)}}
 if(type==='turtle'){main=new THREE.Mesh(new THREE.SphereGeometry(1,8,5),body);main.scale.set(1.25,.55,1.05);}
 if(type==='wyrm'){main=new THREE.Mesh(new THREE.ConeGeometry(1,2,7),body);main.rotation.z=Math.PI/2;main.scale.set(1.4,.6,.6)}
 main.castShadow=true;g.add(main);[-.28,.28].forEach(x=>{const e=new THREE.Mesh(new THREE.SphereGeometry(.1,8,6),eye);e.position.set(x,.25,.82);g.add(e)});return g}
function clearWorld(){while(actors.children.length)actors.remove(actors.children[0]);decor.forEach(o=>world.remove(o));decor=[];creatures=[];player=null;boss=null}
function makeActor({id,stars,isPlayer=false,isBoss=false,x=0,z=0,type='frog'}){const colors=palette[createLevelConfig(state.level).theme],color=isPlayer?0xa7ffd0:(isBoss?colors[2]:new THREE.Color().setHSL((.08+Math.max(stars,1)*.11)%1,.76,.55));const mesh=shapeMesh(type,color);const radius=isBoss?1.35:isPlayer?1.05:.8;mesh.position.set(x,.7,z);mesh.scale.setScalar((isBoss?1.5:1)*(1+Math.max(stars,1)*.07));mesh.userData={id,stars,isPlayer,isBoss,type,shield:isBoss||isPlayer,velocity:new THREE.Vector3(),wander:new THREE.Vector3(),wanderTime:0,dead:false,radius,baseScale:mesh.scale.x,health:isBoss?100:1,respawnTimer:0,label:null};mesh.userData.label=labelSprite(`${isBoss?'WARDEN ':stars===0?'FOOD ':type.toUpperCase()}  ${stars===0?'☆':starsText(stars)}`,isBoss?'#ffe48a':isPlayer?'#baffd7':stars===0?'#c7ff88':'#eaffb5');mesh.add(mesh.userData.label);if(isBoss){const aura=new THREE.Mesh(new THREE.TorusGeometry(1.8,.045,8,40),new THREE.MeshBasicMaterial({color:0xffd66d,transparent:true,opacity:.8}));aura.rotation.x=Math.PI/2;mesh.add(aura);mesh.userData.aura=aura}actors.add(mesh);return mesh}
function starsText(n){return '★'.repeat(Math.min(7,n))+'☆'.repeat(Math.max(0,Math.min(7,7-n)))}
function randomSpawn(min=4,max=14){const a=Math.random()*Math.PI*2,r=min+Math.random()*(max-min);return {x:Math.cos(a)*r,z:Math.sin(a)*r}}
function buildEnvironment(){const cfg=createLevelConfig(state.level),colors=palette[cfg.theme];scene.background=new THREE.Color(colors[0]);scene.fog.color=new THREE.Color(colors[0]);const floor=new THREE.Mesh(new THREE.CircleGeometry(30,64),mat(colors[0]));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;world.add(floor);decor.push(floor);const ring=new THREE.Mesh(new THREE.RingGeometry(10.8,11,96),new THREE.MeshBasicMaterial({color:colors[1],transparent:true,opacity:.35}));ring.rotation.x=-Math.PI/2;world.add(ring);decor.push(ring);for(let i=0;i<26+cfg.hazard*2;i++){const a=Math.random()*Math.PI*2,r=8+Math.random()*16,h=.3+Math.random()*2;const geo=cfg.theme==='crystal'?new THREE.OctahedronGeometry(h):new THREE.DodecahedronGeometry(h*.7);const ob=new THREE.Mesh(geo,mat(colors[i%3],.65,i%3===2?colors[2]:0));ob.position.set(Math.cos(a)*r,h*.5,Math.sin(a)*r);ob.rotation.set(Math.random(),Math.random(),Math.random());ob.castShadow=true;world.add(ob);decor.push(ob)}}
function randomAround(origin,min=8,max=15){const p=randomSpawn(min,max);return {x:origin.x+p.x,z:origin.z+p.z}}
function spawnLevel(){clearWorld();buildEnvironment();const cfg=createLevelConfig(state.level);const start=randomSpawn(2,3);player=makeActor({id:'player',stars:state.stars,isPlayer:true,x:start.x,z:start.z,type:'frog'});boss=makeActor({id:'boss',stars:cfg.bossStars,isBoss:true,x:start.x,z:start.z-5,type:'wyrm'});const foodCount=Math.min(4,cfg.creatures);for(let i=0;i<cfg.creatures;i++){const isFood=i<foodCount;const p=randomAround(start,isFood?7:11,isFood?10:18);const stars=isFood?0:Math.max(1,Math.min(cfg.bossStars-1,1+Math.floor(Math.random()*Math.max(1,cfg.bossStars-1))));creatures.push(makeActor({id:`c${i}`,stars,x:p.x,z:p.z,type:creatureTypes[i%creatureTypes.length]}))}updateHud();}
function updateHud(){const cfg=createLevelConfig(state.level);document.querySelector('#level-name').textContent=cfg.name.toUpperCase();document.querySelector('#level-number').textContent=`${String(state.level).padStart(2,'0')} / 10`;document.querySelector('#player-stars').textContent=starsText(state.stars);document.querySelector('#boss-stars').textContent=starsText(cfg.bossStars);document.querySelector('#growth-label').textContent=`${state.eaten} / ${Math.max(2,3+state.level)}`;document.querySelector('#power-fill').style.width=`${Math.min(100,10+state.stars*8)}%`;document.querySelector('#threat-label').textContent=state.stars>=cfg.bossStars?'APEX':'HUNTING';document.querySelector('#objective-text').textContent=state.eaten===0?'Eat a smaller creature to break the opening shields.':`Defeat the ${cfg.name} Warden with pulse attacks.`;document.querySelector('#boss-card').style.opacity=state.eaten===0?'1':'.82';const bar=document.querySelector('#boss-health-fill');if(bar)bar.style.width=`${Math.max(0,boss?.userData.health||0)}%`}
function nearby(actor){return [...creatures,boss,player].filter(x=>x&&x!==actor&&!x.userData.dead).map(x=>({id:x.userData.id,stars:x.userData.stars,distance:actor.position.distanceTo(x.position)})).filter(x=>x.distance<8)}
function moveActor(a,dt){const u=a.userData;if(u.dead)return;if(u.isBoss){const target=player;const dir=target.position.clone().sub(a.position);dir.y=0;if(dir.length()>2.8)dir.normalize();else dir.set(0,0,0);u.velocity.lerp(dir.multiplyScalar(getStarSpeed(u.stars)*.72),.09);a.position.addScaledVector(u.velocity,dt)}else if(u.isPlayer){const dir=new THREE.Vector3((keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+touchInput.x,0,(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0)+touchInput.z);if(dir.lengthSq())dir.normalize();const boost=(keys.has('ShiftLeft')||keys.has('ShiftRight')||touchInput.boost)?2.3:1;u.velocity.lerp(dir.multiplyScalar(getStarSpeed(u.stars)*boost),.25);a.position.addScaledVector(u.velocity,dt)}else{u.wanderTime-=dt;const intent=chooseTarget(u,nearby(a));const target=intent.id&&[...creatures,boss,player].find(x=>x?.userData.id===intent.id);if(target){const dir=target.position.clone().sub(a.position);dir.y=0;dir.normalize();if(intent.type==='flee')dir.multiplyScalar(-1);u.velocity.lerp(dir.multiplyScalar(getStarSpeed(u.stars)*.7),.08)}else if(u.wanderTime<=0){u.wander.set(Math.random()-.5,0,Math.random()-.5).normalize();u.wanderTime=1+Math.random()*1.5}else u.velocity.lerp(u.wander.multiplyScalar(getStarSpeed(u.stars)*.55),.07);a.position.addScaledVector(u.velocity,dt)}a.position.x=THREE.MathUtils.clamp(a.position.x,-16,16);a.position.z=THREE.MathUtils.clamp(a.position.z,-16,16);const speed=u.velocity.length();a.rotation.y+=dt*(1.5+speed*.35);const squash=1+Math.min(.12,speed*.035)*Math.sin(performance.now()*.018);a.scale.set(u.baseScale*(1/squash),u.baseScale*squash,u.baseScale*(1/squash));if(u.aura)u.aura.rotation.z+=dt*1.8}
function respawnCreature(a){const p=randomAround(player?.position||{x:0,z:0},10,18);a.position.set(p.x,.7,p.z);a.userData.dead=false;a.visible=true;a.userData.respawnTimer=0}
function consumeCreature(a,consumer){a.userData.dead=true;a.visible=false;a.userData.respawnTimer=3+Math.random()*3;if(consumer!==player)consumer.userData.stars++;if(consumer===player){state.eaten++;if(state.eaten>=3){state.stars++;state.eaten=0;consumer.userData.stars=state.stars;toast(`EVOLUTION COMPLETE  ★${state.stars}`);sfx(720,.14)}else{toast(`${a.userData.type.toUpperCase()} FOOD  ${state.eaten}/3`);sfx(480,.1)}updateHud()}else sfx(210,.08)}
function killPlayer(){if(player.userData.dead)return;player.userData.dead=true;player.visible=false;toast('CONSUMED — RETURNING TO SECTOR 01');sfx(90,.25);state={level:1,stars:1,eaten:0};setTimeout(()=>{spawnLevel();running=true},900)}
function resolveCombat(){
  if(!player||player.userData.dead)return;
  const all=[player,boss,...creatures].filter(Boolean);
  for(let i=0;i<all.length;i++){
    for(let j=i+1;j<all.length;j++){
      const a=all[i],b=all[j];
      if(a.userData.dead||b.userData.dead)continue;
      if((a.userData.isBoss&&b.userData.isPlayer||b.userData.isBoss&&a.userData.isPlayer)&&state.eaten===0)continue;
      if(a.position.distanceTo(b.position)>a.userData.radius+b.userData.radius)continue;
      if(!canEat(a.userData.stars,b.userData.stars)&&!canEat(b.userData.stars,a.userData.stars))continue;
      const stronger=canEat(a.userData.stars,b.userData.stars)?a:b;
      const weaker=stronger===a?b:a;
      if(weaker.userData.isBoss)continue;
      if(weaker.userData.isPlayer){killPlayer();continue}
      consumeCreature(weaker,stronger);
    }
  }
}
function pulseAttack(){if(!running||!player||!boss||boss.userData.dead)return;ensureAudio();if(player.position.distanceTo(boss.position)>5){toast('MOVE CLOSER TO THE WARDEN');return}if(state.eaten===0){toast('BREAK THE SHIELDS WITH YOUR FIRST MEAL');return}if(state.stars<boss.userData.stars){toast(`NEED ★${boss.userData.stars} TO HURT THE WARDEN`);return}boss.userData.health-=22;boss.userData.label.material.color.set(0xff9b80);toast(`PULSE HIT  ${Math.max(0,boss.userData.health)}%`);sfx(680,.14);updateHud();if(boss.userData.health<=0){boss.userData.dead=true;boss.visible=false;toast('WARDEN DEFEATED — SECTOR CLEARED');sfx(880,.25);setTimeout(nextLevel,1200)}}
function nextLevel(){if(state.level>=10){toast('THE CROWN IS YOURS — ASCENSION COMPLETE');running=false;document.querySelector('#start-card').classList.remove('hidden');return}state=nextLevelState(state);state.eaten=0;spawnLevel();toast(`SECTOR ${String(state.level).padStart(2,'0')} — ${createLevelConfig(state.level).name.toUpperCase()}`)}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function animate(){requestAnimationFrame(animate);const now=performance.now(),dt=Math.min(.05,(now-last)/1000);last=now;if(running&&!paused){moveActor(player,dt);moveActor(boss,dt);creatures.forEach(a=>{if(a.userData.dead){a.userData.respawnTimer-=dt;if(a.userData.respawnTimer<=0)respawnCreature(a)}else moveActor(a,dt)});resolveCombat();if(pulseQueued){pulseQueued=false;pulseAttack()}camera.position.lerp(new THREE.Vector3(player.position.x*.32,10.5,player.position.z+13.5),.08);camera.lookAt(player.position.x,0,player.position.z)}renderer.render(scene,camera)}
function begin(){document.querySelector('#start-card').classList.add('hidden');running=true;paused=false;ensureAudio();spawnLevel();toast('SHIELDS ACTIVE — EAT TO UNLOCK COMBAT');sfx(340,.12)}
document.querySelector('#start-btn').addEventListener('click',begin);document.querySelector('#resume-btn').addEventListener('click',()=>{paused=false;document.querySelector('#pause-card').classList.add('hidden')});document.querySelector('#sound-toggle').addEventListener('click',()=>{soundOn=!soundOn;document.querySelector('#sound-toggle').textContent=soundOn?'♫':'×';if(soundOn)ensureAudio();if(masterGain)masterGain.gain.value=soundOn?.14:0});
addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='Space'){e.preventDefault();pulseQueued=true}if(e.code==='Escape'&&running){paused=!paused;document.querySelector('#pause-card').classList.toggle('hidden',!paused)}});addEventListener('keyup',e=>keys.delete(e.code));addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
const joystick=document.querySelector('#joystick'),knob=document.querySelector('#joystick-knob');let joystickPointer=null;function updateJoystick(e){const r=joystick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let x=(e.clientX-cx)/(r.width*.34),z=(e.clientY-cy)/(r.height*.34);const len=Math.hypot(x,z);if(len>1){x/=len;z/=len}touchInput.x=x;touchInput.z=z;knob.style.transform=`translate(${x*34}px,${z*34}px)`}joystick.addEventListener('pointerdown',e=>{joystickPointer=e.pointerId;joystick.setPointerCapture(e.pointerId);updateJoystick(e);ensureAudio()});joystick.addEventListener('pointermove',e=>{if(e.pointerId===joystickPointer)updateJoystick(e)});const resetJoystick=()=>{joystickPointer=null;touchInput.x=0;touchInput.z=0;knob.style.transform='translate(0,0)'};joystick.addEventListener('pointerup',resetJoystick);joystick.addEventListener('pointercancel',resetJoystick);const burst=document.querySelector('#touch-burst');burst.addEventListener('pointerdown',()=>{touchInput.boost=true;ensureAudio()});burst.addEventListener('pointerup',()=>touchInput.boost=false);burst.addEventListener('pointercancel',()=>touchInput.boost=false);document.querySelector('#touch-pulse').addEventListener('pointerdown',()=>{pulseQueued=true;ensureAudio()});
spawnLevel();animate();
