import * as THREE from 'three';
import { canEat, chooseTarget, createLevelConfig, getStarSpeed, nextLevelState } from './game/rules.js';
import './styles.css';
import './mobile-controls.css';

const canvas = document.querySelector('#game-canvas');
const scene = new THREE.Scene(); scene.fog = new THREE.FogExp2(0x0b2527, 0.018);
const camera = new THREE.PerspectiveCamera(48, innerWidth / innerHeight, .1, 200); camera.position.set(0, 11, 15);
const renderer = new THREE.WebGLRenderer({ canvas, antialias: true, powerPreference: 'high-performance' });
renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.setSize(innerWidth, innerHeight); renderer.shadowMap.enabled = true; renderer.shadowMap.type = THREE.PCFSoftShadowMap;
scene.add(new THREE.HemisphereLight(0x9cf4d6, 0x07151d, 2.2));
const moon = new THREE.DirectionalLight(0xc5fff0, 3.2); moon.position.set(-9, 16, 6); moon.castShadow = true; scene.add(moon);
const world = new THREE.Group(); scene.add(world); const actors = new THREE.Group(); world.add(actors);
const keys = new Set(); let running = false; let paused = false; let soundOn = true; let audioCtx = null; let masterGain = null; let musicTimer = null; let touchInput = { x: 0, z: 0, boost: false }; let state = { level: 1, stars: 1, eaten: 0 };
let player, boss, creatures = [], decor = [], last = performance.now(), pulse = 0;
const mat = (color, roughness=.6, emissive=0) => new THREE.MeshStandardMaterial({ color, roughness, metalness:.08, emissive, emissiveIntensity: emissive ? 1.3 : 0 });
const palette = { mist: [0x133b3b,0x68dcb8,0x8cffb7], crystal:[0x132d48,0x6dbbff,0xb0f6ff], ember:[0x42211f,0xff8b55,0xffd085], moss:[0x183c2b,0x9bdc65,0xd4ff9a], marsh:[0x27324c,0xb08bff,0xd7c7ff], storm:[0x1d2941,0x7596ff,0xc5d8ff], ruins:[0x473f35,0xcaa36a,0xffe4a4], frost:[0x244b63,0x94e2ff,0xe5fbff], void:[0x27193f,0xe779ff,0xffb7f7], crown:[0x4a3620,0xffcc4d,0xfff1a0] };
function ensureAudio(){ if(!soundOn)return null; const C=window.AudioContext||window.webkitAudioContext; if(!C)return null; if(!audioCtx){audioCtx=new C();masterGain=audioCtx.createGain();masterGain.gain.value=.13;masterGain.connect(audioCtx.destination)} if(audioCtx.state==='suspended')audioCtx.resume(); if(!musicTimer){let step=0;musicTimer=setInterval(()=>{if(!soundOn||!audioCtx)return;const notes=[196,246.94,293.66,246.94];const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='triangle';o.frequency.value=notes[step++%notes.length];g.gain.setValueAtTime(.0001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.055,audioCtx.currentTime+.04);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+1.1);o.connect(g).connect(masterGain);o.start();o.stop(audioCtx.currentTime+1.15)},1200)} return audioCtx; }
function sfx(freq=280,duration=.07){ const ac=ensureAudio(); if(!ac)return; const o=ac.createOscillator(),g=ac.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.15,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+duration);o.connect(g).connect(masterGain);o.start();o.stop(ac.currentTime+duration); }
function clearWorld(){ while(actors.children.length) actors.remove(actors.children[0]); decor.forEach(o=>world.remove(o)); decor=[]; creatures=[]; player=null; boss=null; }
function blobMesh(color, _scale){ const g=new THREE.Group(); const body=new THREE.Mesh(new THREE.SphereGeometry(1,20,14),mat(color,.38,color)); body.scale.set(1.2,.75,1); body.castShadow=true; g.add(body); const eyeMat=mat(0x07151d); [-.28,.28].forEach(x=>{const e=new THREE.Mesh(new THREE.SphereGeometry(.1,10,8),eyeMat);e.position.set(x,.22,.86);g.add(e)}); return g; }
function makeActor({id,stars,isPlayer=false,isBoss=false,x=0,z=0}){ const colors=palette[createLevelConfig(state.level).theme]; const color=isPlayer?0xa7ffd0:(isBoss?colors[2]:new THREE.Color().setHSL(.2+(stars*.08)%1,.75,.56)); const mesh=blobMesh(color,1+stars*.055); mesh.position.set(x,.7,z); mesh.userData={id,stars,isPlayer,isBoss,shield:isBoss||isPlayer,velocity:new THREE.Vector3(),wander:new THREE.Vector3(),wanderTime:0,attackTarget:null,dead:false,baseScale:1+stars*.055}; actors.add(mesh); return mesh; }
function starsText(n){return '★'.repeat(Math.min(7,n))+'☆'.repeat(Math.max(0,Math.min(7,7-n)));}
function buildEnvironment(){ const cfg=createLevelConfig(state.level); const colors=palette[cfg.theme]; scene.background=new THREE.Color(colors[0]); scene.fog.color=new THREE.Color(colors[0]); const floor=new THREE.Mesh(new THREE.CircleGeometry(30,64),mat(colors[0]));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;world.add(floor);decor.push(floor); const ring=new THREE.Mesh(new THREE.RingGeometry(11,11.08,96),new THREE.MeshBasicMaterial({color:colors[1],transparent:true,opacity:.3}));ring.rotation.x=-Math.PI/2;world.add(ring);decor.push(ring);
 for(let i=0;i<30+cfg.hazard*2;i++){const a=Math.random()*Math.PI*2,r=8+Math.random()*16,h=.3+Math.random()*2;let geo=cfg.theme==='crystal'?new THREE.OctahedronGeometry(h):new THREE.DodecahedronGeometry(h*.7);const ob=new THREE.Mesh(geo,mat(colors[i%3],.65, i%3===2?colors[2]:0));ob.position.set(Math.cos(a)*r,h*.5,Math.sin(a)*r);ob.rotation.set(Math.random(),Math.random(),Math.random());ob.castShadow=true;world.add(ob);decor.push(ob)} }
function spawnLevel(){ clearWorld(); buildEnvironment(); const cfg=createLevelConfig(state.level); player=makeActor({id:'player',stars:state.stars,isPlayer:true,x:0,z:4}); boss=makeActor({id:'boss',stars:cfg.bossStars,isBoss:true,x:0,z:-4}); for(let i=0;i<cfg.creatures;i++){const a=Math.random()*Math.PI*2,r=5+Math.random()*14; const stars=Math.max(1,Math.min(cfg.bossStars-1,1+Math.floor(Math.random()*(cfg.bossStars)))); creatures.push(makeActor({id:`c${i}`,stars,x:Math.cos(a)*r,z:Math.sin(a)*r}));} updateHud(); }
function updateHud(){const cfg=createLevelConfig(state.level);document.querySelector('#level-name').textContent=cfg.name.toUpperCase();document.querySelector('#level-number').textContent=`${String(state.level).padStart(2,'0')} / 10`;document.querySelector('#player-stars').textContent=starsText(state.stars);document.querySelector('#boss-stars').textContent=starsText(cfg.bossStars);document.querySelector('#growth-label').textContent=`${state.eaten} / ${Math.max(2,3+state.level)}`;document.querySelector('#power-fill').style.width=`${Math.min(100,10+state.stars*8)}%`;document.querySelector('#threat-label').textContent=state.stars>=cfg.bossStars?'APEX':'LOW';document.querySelector('#objective-text').textContent=state.eaten===0?'Find something smaller. The first meal breaks the shields.':state.level===10?'Defeat the Crown Warden.':'Consume weaker forms to evolve through this sector.';document.querySelector('#boss-card').style.opacity=state.eaten===0?'1':'.55';}
function nearestFor(actor){return [...creatures,boss,player].filter(x=>x&&x!==actor&&!x.userData.dead).map(x=>({id:x.userData.id,stars:x.userData.stars,distance:actor.position.distanceTo(x.position)})).filter(x=>x.distance<5);}
function moveActor(a,dt){const u=a.userData;if(u.dead)return;let intent=chooseTarget(u,nearestFor(a).filter(x=>x.id!=='player'||!u.isPlayer));let target=(intent.id&&[...creatures,boss,player].find(x=>x?.userData.id===intent.id))||null; if(u.isPlayer){let dir=new THREE.Vector3((keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+touchInput.x,0,(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0)+touchInput.z); if(dir.lengthSq())dir.normalize(); let boost=(keys.has('ShiftLeft')||keys.has('ShiftRight')||touchInput.boost)?1.8:1;u.velocity.lerp(dir.multiplyScalar(getStarSpeed(u.stars)*boost),.14); a.position.addScaledVector(u.velocity,dt);a.position.x=THREE.MathUtils.clamp(a.position.x,-15,15);a.position.z=THREE.MathUtils.clamp(a.position.z,-15,15);}else{u.wanderTime-=dt;if(intent.type!=='wander'&&target){const dir=target.position.clone().sub(a.position);dir.y=0;dir.normalize();if(intent.type==='flee')dir.multiplyScalar(-1);u.velocity.lerp(dir.multiplyScalar(getStarSpeed(u.stars)*.55),.025);}else if(u.wanderTime<=0){u.wander.set(Math.random()-.5,0,Math.random()-.5).normalize();u.wanderTime=1+Math.random()*2;}else u.velocity.lerp(u.wander.multiplyScalar(getStarSpeed(u.stars)*.3),.02);a.position.addScaledVector(u.velocity,dt);if(Math.abs(a.position.x)>16||Math.abs(a.position.z)>16)u.wander.multiplyScalar(-1)}a.rotation.y+=dt*1.5;const s=u.baseScale*(1+Math.sin(performance.now()*.004+u.stars)*.035);a.scale.set(s,s,s); }
function tryConsume(){if(!running||!player)return;for(const a of [...creatures,boss]){if(a.userData.dead||!canEat(player.userData.stars,a.userData.stars))continue;if(player.position.distanceTo(a.position)<1.8){if(a.userData.isBoss&&state.eaten===0)continue;a.userData.dead=true;a.visible=false;state.eaten++;if(a.userData.isBoss){toast('WARDEN CONSUMED — SECTOR CLEARED');sfx(640,.2);setTimeout(nextLevel,1200)}else{sfx(480,.08); if(state.eaten>=Math.max(2,3+state.level)){state.stars++;player.userData.stars=state.stars;toast(`EVOLUTION COMPLETE — ★ ${state.stars}`);sfx(720,.14);updateHud()}} updateHud();}}}
function nextLevel(){if(state.level>=10){toast('THE CROWN IS YOURS — ASCENSION COMPLETE');running=false;document.querySelector('#start-card').classList.remove('hidden');document.querySelector('#start-card h1').innerHTML='You are the<br><em>apex star.</em>';document.querySelector('#start-btn').textContent='RESTART EVOLUTION ↗';return}state=nextLevelState(state);state.eaten=0;spawnLevel();toast(`SECTOR ${String(state.level).padStart(2,'0')} — ${createLevelConfig(state.level).name.toUpperCase()}`);}
function toast(msg){const t=document.querySelector('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300)}
function animate(){requestAnimationFrame(animate);const now=performance.now(),dt=Math.min(.05,(now-last)/1000);last=now;if(running&&!paused){moveActor(player,dt);[...creatures,boss].forEach(a=>moveActor(a,dt));tryConsume();camera.position.lerp(new THREE.Vector3(player.position.x*.32,10.5,player.position.z+13.5),.04);camera.lookAt(player.position.x,0,player.position.z);pulse+=dt;document.querySelector('#power-fill').style.filter=`brightness(${1+Math.sin(pulse*3)*.08})`}renderer.render(scene,camera)}animate();
function begin(){document.querySelector('#start-card').classList.add('hidden');running=true;paused=false;ensureAudio();spawnLevel();toast('SHIELDS ACTIVE — MAKE THE FIRST MEAL');sfx(340,.12)}
document.querySelector('#start-btn').addEventListener('click',begin);document.querySelector('#resume-btn').addEventListener('click',()=>{paused=false;document.querySelector('#pause-card').classList.add('hidden')});document.querySelector('#sound-toggle').addEventListener('click',()=>{soundOn=!soundOn;document.querySelector('#sound-toggle').textContent=soundOn?'♫':'×';if(soundOn)ensureAudio();if(masterGain)masterGain.gain.value=soundOn?.13:0});
addEventListener('keydown',(e)=>{keys.add(e.code);if(e.code==='Space'){e.preventDefault();pulse+=.3}if(e.code==='Escape'&&running){paused=!paused;document.querySelector('#pause-card').classList.toggle('hidden',!paused)}});addEventListener('keyup',(e)=>keys.delete(e.code));addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
const joystick=document.querySelector('#joystick'), knob=document.querySelector('#joystick-knob');let joystickPointer=null;function updateJoystick(e){const r=joystick.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2;let x=(e.clientX-cx)/(r.width*.34),z=(e.clientY-cy)/(r.height*.34);const len=Math.hypot(x,z);if(len>1){x/=len;z/=len}touchInput.x=x;touchInput.z=z;knob.style.transform=`translate(${x*34}px,${z*34}px)`}joystick.addEventListener('pointerdown',e=>{joystickPointer=e.pointerId;joystick.setPointerCapture(e.pointerId);updateJoystick(e);ensureAudio()});joystick.addEventListener('pointermove',e=>{if(e.pointerId===joystickPointer)updateJoystick(e)});const resetJoystick=()=>{joystickPointer=null;touchInput.x=0;touchInput.z=0;knob.style.transform='translate(0,0)'};joystick.addEventListener('pointerup',resetJoystick);joystick.addEventListener('pointercancel',resetJoystick);const burst=document.querySelector('#touch-burst');burst.addEventListener('pointerdown',()=>{touchInput.boost=true;ensureAudio()});burst.addEventListener('pointerup',()=>{touchInput.boost=false});burst.addEventListener('pointercancel',()=>{touchInput.boost=false});document.querySelector('#touch-pulse').addEventListener('pointerdown',()=>{pulse+=.3;sfx(360,.08);ensureAudio()});
spawnLevel();
